site_name: Aplicação de Redes de Computadores
site_author: Bruno Pithon

theme:
  name: material
  language: pt
  
repo_name: brunopithon/apr-2023-2
repo_url: https://github.com/brunopithon/apr-2023-2

nav:
- index.md
- pedra.md
- papel.md
- tesoura.md

- Ensaios:
  - mermaid.md

plugins:
    - mermaid2